### ISSUE TITLE
Where is config.json ?

### ISSUE THREAD

**Issue by seaSide974** [koltyakov/generator-sppp#15]
In the readme you mentionned : 
"Communication layer settings are stored in ./config/private.json, parameters settings description can be found here." The link is 404

**Comment by koltyakov** [comment]
Thanks! Fixed the readme.
Since the times the tooling evolved and parts of the docs are out of the date.
The link should be https://github.com/s-KaiNet/node-sp-auth/wiki
Now there is even no need in manual changed of the private.json(s) as there is a utility.
Within generated project `npm run config` triggers cli wizard. Which is in it's way is powered with `node-sp-auth-config`.

**Comment by seaSide974** [comment]
Thank you ! Ill try using the yo commands then :)
