### ISSUE TITLE
Watch with multiple entry points

### ISSUE THREAD

**Issue by clechner77** [koltyakov/generator-sppp#32]
In my projects, I setup each webpart to have it's own entry point, a dedicated folder under SCRIPTS and a dedicated hbs file under WEBPARTS.

My issue is that if I run "gulp watch --prod" the first time a change is made and saved, it rebuilds ALL webarts/entry points.  After that, however, it works how I would expect, only rebuilding the webpart/entry point for which the change is made.  Note - I believe I did need to remove COPYASSETSMAP and any entries or else it does rebuild all after every change.

I wonder if it's possible to eliminate that first rebuild of all when starting watch?

**Comment by koltyakov** [comment]
Hi @clechner77,

Only the changed webpart `.hbs` is built during the watch, even on a first change. So I assume you're mostly mentioning JS/TS.

Regarding JS/TS entry points and watch, this is how Webpack watches, before tracking incremental changes it has, in my knowledge, to build everything, otherwise, it's even not obvious how to track a change. Imagine a change in a JS which is imported in another JS which is imported... you got an idea.

In projects with a larger code base and many entry points when build time is relevantly bloated and becomes not comfortable, especially as you know that within many only some entry points are at active development, there is a special parameter in sp-build-tasks which reduces the active entry points.

Not sure that I documented this, but we use that parameter for scoping entry points all over the projects.

To limit an entry point you can start `watch`, or `build`, or `start` commands with `--webpack-targets` argument:

```bash
gulp watch --webpack-targets=target1.js,target2.js
```

Where `target1.js` and so on is a target from app.js/webpackItemsMap/*.

**Comment by clechner77** [comment]
This is EXACTLY what I was looking for.   Thank you!  I'm not sure if that parameter is documented.  I looked around but probably missed it.

**Comment by koltyakov** [comment]
Closing the issue. Documented in sp-build-tasks [Wiki page](https://github.com/koltyakov/sp-build-tasks/wiki/Build-options:-Limiting-Webpack-entry-points).
